//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.17 at 11:12:09 AM GMT+08:00 
//


package org.geektimes.enterprise.inject.standard.beans.xml.bind;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="class" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stereotype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "clazzOrStereotype"
})
@XmlRootElement(name = "alternatives")
public class Alternatives {

    @XmlElementRefs({
            @XmlElementRef(name = "class", namespace = "http://xmlns.jcp.org/xml/ns/javaee", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "stereotype", namespace = "http://xmlns.jcp.org/xml/ns/javaee", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<String>> clazzOrStereotype;

    /**
     * Gets the value of the clazzOrStereotype property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the clazzOrStereotype property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClazzOrStereotype().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public List<JAXBElement<String>> getClazzOrStereotype() {
        if (clazzOrStereotype == null) {
            clazzOrStereotype = new ArrayList<JAXBElement<String>>();
        }
        return this.clazzOrStereotype;
    }

}
